version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
      - mongodb
      - redis
      - rabbitmq
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sqlpaafff
      POSTGRES_DB: db_gofiber
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MONGODB_URI: mongodb://mongodb:27017
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ''
      REDIS_DB: 0
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
      JWT_SECRET: rahasia-paafff

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sqlpaafff
      POSTGRES_DB: db_gofiber
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
